export const Routes = {
  admins: '/admin-ui/admins',
  admin: { route: '/admin-ui/admins/:id', to: (adminId: string) => `/admin-ui/admins/${adminId}` },
  adminNew: '/admin-ui/admins/new',
  assets: '/admin-ui/assets',
  channels: '/admin-ui/channels',
  channel: { route: '/admin-ui/channels/:id', to: (channelId: string) => `/admin-ui/channels/${channelId}` },
  channelNew: '/admin-ui/channels/new',
  collections: '/admin-ui/collections',
  collection: {
    route: '/admin-ui/collections/:id',
    to: (collectionId: string) => `/admin-ui/collections/${collectionId}`,
  },
  collectionNew: '/admin-ui/collections/new',
  countries: '/admin-ui/countries',
  customers: '/admin-ui/customers',
  customer: { route: '/admin-ui/customers/:id', to: (customerId: string) => `/admin-ui/customers/${customerId}` },
  dashboard: '/admin-ui',
  facets: '/admin-ui/facets',
  facet: { route: '/admin-ui/facets/:id', to: (facetId: string) => `/admin-ui/facets/${facetId}` },
  facetNew: '/admin-ui/facets/new',
  orders: '/admin-ui/orders',
  order: { route: '/admin-ui/orders/:id', to: (orderId: string) => `/admin-ui/orders/${orderId}` },
  paymentMethods: '/admin-ui/payment-methods',
  paymentMethod: {
    route: '/admin-ui/payment-methods/:id',
    to: (methodId: string) => `/admin-ui/payment-methods/${methodId}`,
  },
  paymentMethodNew: '/admin-ui/payment-methods/new',
  products: '/admin-ui/products',
  product: { route: '/admin-ui/products/:id', to: (productId: string) => `/admin-ui/products/${productId}` },
  productNew: '/admin-ui/products/new',
  roles: '/admin-ui/roles',
  role: { route: '/admin-ui/roles/:id', to: (roleId: string) => `/admin-ui/roles/${roleId}` },
  roleNew: '/admin-ui/roles/new',
  sellers: '/admin-ui/sellers',
  seller: {
    route: '/admin-ui/sellers/:id',
    to: (sellerId: string) => `/admin-ui/sellers/${sellerId}`,
  },
  sellerNew: '/admin-ui/sellers/new',
  shippingMethods: '/admin-ui/shipping-methods',
  shippingMethod: {
    route: '/admin-ui/shipping-methods/:id',
    to: (methodId: string) => `/admin-ui/shipping-methods/${methodId}`,
  },
  shippingMethodNew: '/admin-ui/shipping-methods/new',
  stockLocations: '/admin-ui/stocks',
  stockLocation: {
    route: '/admin-ui/stocks/:id',
    to: (stockId: string) => `/admin-ui/stocks/${stockId}`,
  },
  stockLocationNew: '/admin-ui/stocks/new',
  taxCategories: '/admin-ui/tax-categories',
  taxCategory: {
    route: '/admin-ui/tax-categories/:id',
    to: (taxCategoryId: string) => `/admin-ui/tax-categories/${taxCategoryId}`,
  },
  taxCategoryNew: '/admin-ui/tax-categories/new',
  taxRates: '/admin-ui/tax-rates',
  taxRate: {
    route: '/admin-ui/tax-rates/:id',
    to: (taxRateId: string) => `/admin-ui/tax-rates/${taxRateId}`,
  },
  taxRateNew: '/admin-ui/tax-rates/new',
  zones: '/admin-ui/zones',
  zone: { route: '/admin-ui/zones/:id', to: (zoneId: string) => `/admin-ui/zones/${zoneId}` },
  zoneNew: '/admin-ui/zones/new',
} as const;
