include:
  - project: 'ci/templates/node'
    file: ['pnpm-publish-public.yml']
  - project: 'ci/templates/docker'
    file: ['monorepo.yml']
    inputs:
      disable_build_deps: true
      matrix:
        - APP: docs
          APP_ROOT: .
          DOCKERFILE: apps/docs/Dockerfile

.build_artifacts: &build_artifacts
  artifacts:
    paths:
      - packages/*/lib
      - packages/*/dist
      - packages/*/cli
      - packages/*/package
      - packages/*/client
      - packages/*/assets
      - packages/*/compiler
      - plugins/*/dist
      - plugins/*/lib
      - plugins/*/package
    expire_in: 1 week

build:
  <<: *build_artifacts

test:
  <<: *build_artifacts
  variables:
    POSTGRES_DB: deenruv
    PGDATABASE: $POSTGRES_DB
    POSTGRES_USER: deenruv
    PGUSER: $POSTGRES_USER
    POSTGRES_PASSWORD: deenruv
    PGPASSWORD: $POSTGRES_PASSWORD
    POSTGRES_HOST_AUTH_METHOD: trust
    PGHOST: postgres
    DB_SCHEMA: public
  services:
    - name: postgres
      alias: postgres

lint:
  <<: *build_artifacts

publish:
  extends: .common
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
    - if: $CI_COMMIT_TAG =~ /^[^\/]+\/v[0-9]+\.[0-9]+\.[0-9]+$/
      exists:
        - pnpm-workspace.yaml
  script:
    - export PUBLISH_SCOPE="@${PUBLISH_SCOPE:-$CI_PROJECT_NAMESPACE}"
    - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
    - echo '.pnpm-store' >> .gitignore
    - pnpm --if-present build
    - npm set registry https://registry.npmjs.org/
    - npm config delete "@${CI_PROJECT_NAMESPACE}:registry" || true
    - npm config delete "${PUBLISH_SCOPE}:registry" || true
    - |
      [ -f pnpm-workspace.yaml ] \
        &&
          (
            export PKGS="$(echo "$CI_COMMIT_TAG" | sed -E 's/[/]?v[0-9]+\.[0-9]+\.[0-9]+$//g')" \
            && pnpm --filter "${PUBLISH_SCOPE}/${PKGS:-*}" publish --access public --no-git-checks
          ) \
        || pnpm publish --no-git-checks --access public
        
deploy docker dev:
  needs: []

deploy docker qa:
  needs: []

deploy docker prod:
  needs: []