packages:
  - packages/*
  - plugins/*
  - apps/*
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - better-sqlite3
  - esbuild
  - husky
  - msgpackr-extract
  - nice-napi
  - protobufjs
  - puppeteer
  - sharp
  - sqlite3