/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	ObjectId: `scalar.ObjectId` as const,
	S3Scalar: `scalar.S3Scalar` as const,
	Timestamp: `scalar.Timestamp` as const,
	ModelNavigationCompiled: `scalar.ModelNavigationCompiled` as const,
	PageInput:{

	},
	ModifyVersion:{
		from:"Timestamp",
		to:"Timestamp"
	},
	ImageFieldInput:{
		thumbnail:"S3Scalar",
		url:"S3Scalar"
	},
	CreateRootCMSParam:{

	},
	MediaParamsInput:{
		page:"PageInput"
	},
	UploadFileInput:{

	},
	InputCMSField:{
		type:"CMSType",
		fields:"InputCMSField"
	},
	Languages: "enum" as const,
	BackupFile: `scalar.BackupFile` as const,
	AdminQuery:{
		analytics:{

		}
	},
	CMSType: "enum" as const,
	Query:{
		listhomepage:{
			rootParams:"RootParamsInput"
		},
		listPaginatedhomepage:{
			page:"PageInput",
			rootParams:"RootParamsInput"
		},
		onehomepageBySlug:{
			rootParams:"RootParamsInput"
		},
		variantshomepageBySlug:{

		},
		listmodel_jarka:{
			rootParams:"RootParamsInput"
		},
		listPaginatedmodel_jarka:{
			page:"PageInput",
			rootParams:"RootParamsInput"
		},
		onemodel_jarkaBySlug:{
			rootParams:"RootParamsInput"
		},
		variantsmodel_jarkaBySlug:{

		},
		listo_nas:{
			rootParams:"RootParamsInput"
		},
		listPaginatedo_nas:{
			page:"PageInput",
			rootParams:"RootParamsInput"
		},
		oneo_nasBySlug:{
			rootParams:"RootParamsInput"
		},
		variantso_nasBySlug:{

		},
		listtestmodel:{
			rootParams:"RootParamsInput"
		},
		listPaginatedtestmodel:{
			page:"PageInput",
			rootParams:"RootParamsInput"
		},
		onetestmodelBySlug:{
			rootParams:"RootParamsInput"
		},
		variantstestmodelBySlug:{

		},
		listtestqa:{
			rootParams:"RootParamsInput"
		},
		listPaginatedtestqa:{
			page:"PageInput",
			rootParams:"RootParamsInput"
		},
		onetestqaBySlug:{
			rootParams:"RootParamsInput"
		},
		variantstestqaBySlug:{

		},
		listtext_page:{
			rootParams:"RootParamsInput"
		},
		listPaginatedtext_page:{
			page:"PageInput",
			rootParams:"RootParamsInput"
		},
		onetext_pageBySlug:{
			rootParams:"RootParamsInput"
		},
		variantstext_pageBySlug:{

		},
		mediaQuery:{
			mediaParams:"MediaParamsInput",
			rootParams:"RootParamsInput"
		},
		filesQuery:{
			mediaParams:"MediaParamsInput",
			rootParams:"RootParamsInput"
		}
	},
	AdminMutation:{
		upsertModel:{
			fields:"InputCMSField"
		},
		removeModel:{

		},
		upsertParam:{
			param:"CreateRootCMSParam"
		},
		removeParam:{

		},
		uploadFile:{
			file:"UploadFileInput"
		},
		uploadImage:{
			file:"UploadFileInput"
		},
		removeFiles:{

		},
		restore:{
			backup:"BackupFile"
		},
		generateApiKey:{

		},
		revokeApiKey:{

		},
		translateDocument:{
			resultLanguages:"Languages"
		},
		changeLogo:{

		},
		upserthomepage:{
			homepage:"Modifyhomepage",
			rootParams:"RootParamsInput"
		},
		removehomepage:{
			rootParams:"RootParamsInput"
		},
		upsertmodel_jarka:{
			model_jarka:"Modifymodel_jarka",
			rootParams:"RootParamsInput"
		},
		removemodel_jarka:{
			rootParams:"RootParamsInput"
		},
		upserto_nas:{
			o_nas:"Modifyo_nas",
			rootParams:"RootParamsInput"
		},
		removeo_nas:{
			rootParams:"RootParamsInput"
		},
		upserttestmodel:{
			testmodel:"Modifytestmodel",
			rootParams:"RootParamsInput"
		},
		removetestmodel:{
			rootParams:"RootParamsInput"
		},
		upserttestqa:{
			testqa:"Modifytestqa",
			rootParams:"RootParamsInput"
		},
		removetestqa:{
			rootParams:"RootParamsInput"
		},
		upserttext_page:{
			text_page:"Modifytext_page",
			rootParams:"RootParamsInput"
		},
		removetext_page:{
			rootParams:"RootParamsInput"
		}
	},
	ModifyhomepageTestobjTestinsideobj:{
		_version:"ModifyVersion"
	},
	ModifyhomepageTestobj:{
		_version:"ModifyVersion",
		testinsideobj:"ModifyhomepageTestobjTestinsideobj"
	},
	Modifyhomepage:{
		_version:"ModifyVersion",
		testowe:"ImageFieldInput",
		testobj:"ModifyhomepageTestobj"
	},
	Modifymodel_jarkaDetails:{
		_version:"ModifyVersion"
	},
	Modifymodel_jarka:{
		_version:"ModifyVersion",
		thumbnail:"ImageFieldInput",
		details:"Modifymodel_jarkaDetails",
		attachments:"S3Scalar"
	},
	Modifyo_nas:{
		_version:"ModifyVersion"
	},
	Modifytestmodel:{
		_version:"ModifyVersion",
		testimage:"ImageFieldInput"
	},
	Modifytestqa:{
		_version:"ModifyVersion"
	},
	Modifytext_page:{
		_version:"ModifyVersion"
	},
	RootParamsInput:{

	},
	CMSModelTypes: "enum" as const
}

export const ReturnTypes: Record<string,any> = {
	ObjectId: `scalar.ObjectId` as const,
	S3Scalar: `scalar.S3Scalar` as const,
	Timestamp: `scalar.Timestamp` as const,
	ModelNavigationCompiled: `scalar.ModelNavigationCompiled` as const,
	VersionField:{
		name:"String",
		from:"Timestamp",
		to:"Timestamp"
	},
	ImageField:{
		url:"S3Scalar",
		thumbnail:"S3Scalar",
		alt:"String"
	},
	RootCMSParam:{
		name:"String",
		options:"String"
	},
	ModelNavigation:{
		name:"String",
		display:"String",
		fields:"CMSField",
		fieldSet:"String"
	},
	CMSField:{
		name:"String",
		type:"CMSType",
		list:"Boolean",
		options:"String",
		relation:"String",
		fields:"CMSField",
		builtIn:"Boolean"
	},
	PageInfo:{
		total:"Int",
		hasNext:"Boolean"
	},
	AnalyticsResponse:{
		date:"String",
		value:"AnalyticsModelResponse"
	},
	AnalyticsModelResponse:{
		modelName:"String",
		calls:"Int",
		rootParamsKey:"String"
	},
	FileResponse:{
		key:"String",
		cdnURL:"String"
	},
	FileConnection:{
		items:"FileResponse",
		pageInfo:"PageInfo"
	},
	MediaResponse:{
		key:"String",
		cdnURL:"String",
		thumbnailCdnURL:"String",
		alt:"String"
	},
	MediaConnection:{
		items:"MediaResponse",
		pageInfo:"PageInfo"
	},
	UploadFileResponseBase:{
		key:"String",
		putURL:"String",
		cdnURL:"String",
		alt:"String"
	},
	ImageUploadResponse:{
		file:"UploadFileResponseBase",
		thumbnail:"UploadFileResponseBase"
	},
	ApiKey:{
		name:"String",
		createdAt:"String",
		_id:"ObjectId",
		value:"String"
	},
	BackupFile: `scalar.BackupFile` as const,
	AdminQuery:{
		analytics:"AnalyticsResponse",
		backup:"Boolean",
		backups:"MediaResponse",
		apiKeys:"ApiKey"
	},
	TranslateDocumentResponse:{
		result:"String",
		usedTokens:"Int"
	},
	Mutation:{
		admin:"AdminMutation"
	},
	Query:{
		navigation:"ModelNavigation",
		rootParams:"RootCMSParam",
		admin:"AdminQuery",
		isLoggedIn:"Boolean",
		logoURL:"String",
		listhomepage:"homepage",
		listPaginatedhomepage:"homepage__Connection",
		onehomepageBySlug:"homepage",
		variantshomepageBySlug:"homepage",
		fieldSethomepage:"String",
		modelhomepage:"ModelNavigationCompiled",
		listmodel_jarka:"model_jarka",
		listPaginatedmodel_jarka:"model_jarka__Connection",
		onemodel_jarkaBySlug:"model_jarka",
		variantsmodel_jarkaBySlug:"model_jarka",
		fieldSetmodel_jarka:"String",
		modelmodel_jarka:"ModelNavigationCompiled",
		listo_nas:"o_nas",
		listPaginatedo_nas:"o_nas__Connection",
		oneo_nasBySlug:"o_nas",
		variantso_nasBySlug:"o_nas",
		fieldSeto_nas:"String",
		modelo_nas:"ModelNavigationCompiled",
		listtestmodel:"testmodel",
		listPaginatedtestmodel:"testmodel__Connection",
		onetestmodelBySlug:"testmodel",
		variantstestmodelBySlug:"testmodel",
		fieldSettestmodel:"String",
		modeltestmodel:"ModelNavigationCompiled",
		listtestqa:"testqa",
		listPaginatedtestqa:"testqa__Connection",
		onetestqaBySlug:"testqa",
		variantstestqaBySlug:"testqa",
		fieldSettestqa:"String",
		modeltestqa:"ModelNavigationCompiled",
		listtext_page:"text_page",
		listPaginatedtext_page:"text_page__Connection",
		onetext_pageBySlug:"text_page",
		variantstext_pageBySlug:"text_page",
		fieldSettext_page:"String",
		modeltext_page:"ModelNavigationCompiled",
		mediaQuery:"MediaConnection",
		filesQuery:"FileConnection"
	},
	AdminMutation:{
		upsertModel:"Boolean",
		removeModel:"Boolean",
		upsertParam:"Boolean",
		removeParam:"Boolean",
		uploadFile:"UploadFileResponseBase",
		uploadImage:"ImageUploadResponse",
		removeFiles:"Boolean",
		restore:"Boolean",
		generateApiKey:"Boolean",
		revokeApiKey:"Boolean",
		translateDocument:"TranslateDocumentResponse",
		changeLogo:"Boolean",
		removeLogo:"Boolean",
		upserthomepage:"Boolean",
		removehomepage:"Boolean",
		upsertmodel_jarka:"Boolean",
		removemodel_jarka:"Boolean",
		upserto_nas:"Boolean",
		removeo_nas:"Boolean",
		upserttestmodel:"Boolean",
		removetestmodel:"Boolean",
		upserttestqa:"Boolean",
		removetestqa:"Boolean",
		upserttext_page:"Boolean",
		removetext_page:"Boolean"
	},
	homepageTestobjTestinsideobj:{
		_version:"VersionField",
		deepfield:"String"
	},
	homepageTestobjTestinsideobj__Connection:{
		items:"homepageTestobjTestinsideobj",
		pageInfo:"PageInfo"
	},
	homepageTestobj:{
		_version:"VersionField",
		testfield:"String",
		testinsideobj:"homepageTestobjTestinsideobj"
	},
	homepageTestobj__Connection:{
		items:"homepageTestobj",
		pageInfo:"PageInfo"
	},
	homepage:{
		_version:"VersionField",
		tytul:"String",
		edycja_nazwy:"String",
		testowe:"ImageField",
		testobj:"homepageTestobj",
		locales:"String",
		slug:"String",
		_id:"String"
	},
	homepage__Connection:{
		items:"homepage",
		pageInfo:"PageInfo"
	},
	model_jarkaDetails:{
		_version:"VersionField",
		size:"String",
		tags:"String",
		weight:"Float"
	},
	model_jarkaDetails__Connection:{
		items:"model_jarkaDetails",
		pageInfo:"PageInfo"
	},
	model_jarka:{
		_version:"VersionField",
		title:"String",
		description:"String",
		content:"String",
		thumbnail:"ImageField",
		details:"model_jarkaDetails",
		attachments:"S3Scalar",
		locales:"String",
		slug:"String",
		_id:"String"
	},
	model_jarka__Connection:{
		items:"model_jarka",
		pageInfo:"PageInfo"
	},
	o_nas:{
		_version:"VersionField",
		locales:"String",
		slug:"String",
		_id:"String"
	},
	o_nas__Connection:{
		items:"o_nas",
		pageInfo:"PageInfo"
	},
	testmodel:{
		_version:"VersionField",
		title:"String",
		num:"Float",
		tete:"String",
		testimage:"ImageField",
		locales:"String",
		slug:"String",
		_id:"String"
	},
	testmodel__Connection:{
		items:"testmodel",
		pageInfo:"PageInfo"
	},
	testqa:{
		_version:"VersionField",
		test:"String",
		test2:"Float",
		locales:"String",
		slug:"String",
		_id:"String"
	},
	testqa__Connection:{
		items:"testqa",
		pageInfo:"PageInfo"
	},
	text_page:{
		_version:"VersionField",
		content:"String",
		locales:"String",
		slug:"String",
		_id:"String"
	},
	text_page__Connection:{
		items:"text_page",
		pageInfo:"PageInfo"
	}
}

export const Ops = {
query: "Query" as const,
	mutation: "Mutation" as const
}