export const Routes = {
    dashboard: '/admin-ui',
    assets: {
        list: '/admin-ui/assets',
    },
    productVariants: {
        list: '/admin-ui/product-variants',
        new: '/admin-ui/product-variants/new',
        route: '/admin-ui/product-variants/:id',
        to: (productVariantId: string) => `/admin-ui/product-variants/${productVariantId}`,
    },
    countries: {
        list: '/admin-ui/countries',
        new: '/admin-ui/countries/new',
        route: '/admin-ui/countries/:id',
        to: (countryId: string) => `/admin-ui/countries/${countryId}`,
    },
    admins: {
        list: '/admin-ui/admins',
        new: '/admin-ui/admins/new',
        route: '/admin-ui/admins/:id',
        to: (id: string) => `/admin-ui/admins/${id}`,
    },
    channels: {
        list: '/admin-ui/channels',
        new: '/admin-ui/channels/new',
        route: '/admin-ui/channels/:id',
        to: (channelId: string) => `/admin-ui/channels/${channelId}`,
    },
    collections: {
        list: '/admin-ui/collections',
        new: '/admin-ui/collections/new',
        route: '/admin-ui/collections/:id',
        to: (collectionId: string) => `/admin-ui/collections/${collectionId}`,
    },
    customers: {
        list: '/admin-ui/customers',
        new: '/admin-ui/customers/new',
        route: '/admin-ui/customers/:id',
        to: (customerId: string) => `/admin-ui/customers/${customerId}`,
    },
    facets: {
        list: '/admin-ui/facets',
        new: '/admin-ui/facets/new',
        route: '/admin-ui/facets/:id',
        to: (facetId: string) => `/admin-ui/facets/${facetId}`,
    },
    orders: {
        list: '/admin-ui/orders',
        new: '/admin-ui/orders/new',
        route: '/admin-ui/orders/:id',
        to: (orderId: string) => `/admin-ui/orders/${orderId}`,
    },
    paymentMethods: {
        list: '/admin-ui/payment-methods',
        new: '/admin-ui/payment-methods/new',
        route: '/admin-ui/payment-methods/:id',
        to: (methodId: string) => `/admin-ui/payment-methods/${methodId}`,
    },
    products: {
        list: '/admin-ui/products',
        new: '/admin-ui/products/new',
        route: '/admin-ui/products/:id',
        to: (productId: string) => `/admin-ui/products/${productId}`,
    },
    promotions: {
        list: '/admin-ui/promotions',
        new: '/admin-ui/promotions/new',
        route: '/admin-ui/promotions/:id',
        to: (promotionId: string) => `/admin-ui/promotions/${promotionId}`,
    },
    roles: {
        list: '/admin-ui/roles',
        new: '/admin-ui/roles/new',
        route: '/admin-ui/roles/:id',
        to: (roleId: string) => `/admin-ui/roles/${roleId}`,
    },
    sellers: {
        list: '/admin-ui/sellers',
        new: '/admin-ui/sellers/new',
        route: '/admin-ui/sellers/:id',
        to: (sellerId: string) => `/admin-ui/sellers/${sellerId}`,
    },
    shippingMethods: {
        list: '/admin-ui/shipping-methods',
        new: '/admin-ui/shipping-methods/new',
        route: '/admin-ui/shipping-methods/:id',
        to: (methodId: string) => `/admin-ui/shipping-methods/${methodId}`,
    },
    stockLocations: {
        list: '/admin-ui/stock-locations',
        new: '/admin-ui/stock-locations/new',
        route: '/admin-ui/stock-locations/:id',
        to: (stockId: string) => `/admin-ui/stock-locations/${stockId}`,
    },
    taxCategories: {
        list: '/admin-ui/tax-categories',
        new: '/admin-ui/tax-categories/new',
        route: '/admin-ui/tax-categories/:id',
        to: (taxCategoryId: string) => `/admin-ui/tax-categories/${taxCategoryId}`,
    },
    taxRates: {
        list: '/admin-ui/tax-rates',
        new: '/admin-ui/tax-rates/new',
        route: '/admin-ui/tax-rates/:id',
        to: (taxRateId: string) => `/admin-ui/tax-rates/${taxRateId}`,
    },
    zones: {
        list: '/admin-ui/zones',
        new: '/admin-ui/zones/new',
        route: '/admin-ui/zones/:id',
        to: (zoneId: string) => `/admin-ui/zones/${zoneId}`,
    },
} as const;
