/**
 * Canonical UI version sourced from `@deenruv/react-ui-devkit` package.json.
 * Used as the single source of truth across admin-dashboard, plugin UIs, and docs.
 *
 * AUTO-GENERATED by generate-version.mjs — do not edit manually.
 */
export const DEENRUV_UI_VERSION: string = '1.0.0';
