/**
 * Build-time script that reads the version from package.json and writes
 * src/version.ts with a string literal constant.
 *
 * This avoids a runtime `import pkg from '../package.json'` which leaks
 * a JSON-module dependency into the published .d.ts files and breaks
 * downstream consumers that don't enable `resolveJsonModule`.
 *
 * Usage: node generate-version.mjs
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(__dirname, "package.json"), "utf-8"));

const content = `/**
 * Canonical UI version sourced from \`@deenruv/react-ui-devkit\` package.json.
 * Used as the single source of truth across admin-dashboard, plugin UIs, and docs.
 *
 * AUTO-GENERATED by generate-version.mjs — do not edit manually.
 */
export const DEENRUV_UI_VERSION: string = '${pkg.version}';
`;

const outPath = join(__dirname, "src", "version.ts");
const existing = existsSync(outPath) ? readFileSync(outPath, "utf-8") : null;

if (existing === content) {
  console.log(
    `[generate-version] DEENRUV_UI_VERSION = '${pkg.version}' (unchanged)`,
  );
} else {
  writeFileSync(outPath, content, "utf-8");
  console.log(`[generate-version] wrote DEENRUV_UI_VERSION = '${pkg.version}'`);
}
