import {
    Building,
    Hexagon,
    Info,
    Shield,
    Users,
    History,
    Tag,
    Cog,
    Truck,
    ClipboardCheck,
    Calculator,
    Database,
    Image,
    Group,
    Layers,
    Activity,
    Cone,
} from 'lucide-react';

export const CardIcons = {
    asset: Image,
    basic: Info,
    default: Hexagon,
    permissions: Shield,
    address: Building,
    users: Users,
    history: History,
    tag: Tag,
    options: Cog,
    shipping: Truck,
    check: ClipboardCheck,
    calc: Calculator,
    customFields: Database,
    group: Group,
    stock: Layers,
    action: Activity,
    filter: Cone,
};
